=== pablosproject/chess-player/Extra/Observador/configura.dtd
<!ELEMENT Opcions (Servidor,Preferencies)>
<!ELEMENT Servidor (Direccio,Port)>
<!ELEMENT Direccio EMPTY>
<!ATTLIST Direccio IP CDATA #REQUIRED>
<!ELEMENT Port EMPTY>
<!ATTLIST Port Servidor CDATA #REQUIRED>
<!ELEMENT Preferencies (Animacions,Fitxes,Idioma,Orientacio,So)>
<!ELEMENT Animacions EMPTY>
<!ATTLIST Animacions Activades CDATA #REQUIRED>
<!ELEMENT Fitxes (Blanques,Negres)>
<!ELEMENT Blanques EMPTY>
<!ATTLIST Blanques Path CDATA "">
<!ELEMENT Negres EMPTY>
<!ATTLIST Negres Path CDATA "">	 
<!ELEMENT Idioma EMPTY>
<!ATTLIST Idioma Seleccionat CDATA #REQUIRED>
<!ELEMENT Orientacio EMPTY>
<!ATTLIST Orientacio Tauler CDATA #REQUIRED>
<!ELEMENT So EMPTY>
<!ATTLIST So Activat CDATA #REQUIRED>

=== pablosproject/chess-player/Extra/Observador/configura.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Opcions SYSTEM "configura.dtd">
<Opcions>
    <!-- ***** Configuració de les dades de connexió al servidor *****	-->
    <Servidor>
        <Direccio IP="127.0.0.1" />
        <Port Servidor="9001" />
    </Servidor>
    <!-- ***** Configuració de preferències del joc per l'usuari *****-->
    <Preferencies>
        <!--Activa o desactiva les animacions durant la partida, Sí o No -->
        <Animacions Activades="No" />
        <!--Path de les imatges dels tipus de fitxes que es fan servir      -->
        <Fitxes>
            <Blanques Path="./Fitxes/Blanques_gif" />
            <Negres Path="./Fitxes/Negres_gif" />
        </Fitxes>
        <!--Idioma de l'aplicació: Català, Castellà, Anglès o Francès    -->
        <Idioma Seleccionat="Català" />
        <!--Orientació de les fitxes cap a l'usuari, Blanques o Negres   -->
        <Orientacio Tauler="Blanques" />
        <!--Activa o desactiva els sons durant la partida, Sí o No       -->
        <So Activat="No" />
    </Preferencies>
</Opcions>
