=== pablosproject/chess-player/Extra/Servidor/configura.dtd
<!ELEMENT Server (Configuracio,Jugadors)>
<!ELEMENT Configuracio (Port,Maxim,Ports,Usuaris)>
<!ELEMENT Port EMPTY>
<!ATTLIST Port Base CDATA #REQUIRED>
<!ELEMENT Maxim EMPTY>
<!ATTLIST Maxim Partides CDATA #REQUIRED>
<!ELEMENT Ports EMPTY>
<!ATTLIST Ports Partida CDATA #REQUIRED>
<!ATTLIST Ports Chat CDATA #REQUIRED>
<!ELEMENT Usuaris EMPTY>
<!ATTLIST Usuaris Registrats CDATA #REQUIRED>
<!ELEMENT Jugadors (Jugador*)>
<!ELEMENT Jugador (Nom,Cognom,Login,Password,Mail,Punts,Partides,Connexio)>
<!ELEMENT Nom (#PCDATA) >
<!ELEMENT Cognom (#PCDATA)>
<!ELEMENT Login (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT Mail (#PCDATA)>
<!ELEMENT Punts (#PCDATA)>
<!ELEMENT Partides (Guanyades,Perdudes,Abandonades,Taules)>
<!ELEMENT Guanyades (#PCDATA)>
<!ELEMENT Perdudes (#PCDATA)>
<!ELEMENT Abandonades (#PCDATA)>
<!ELEMENT Taules (#PCDATA)>
<!ELEMENT Connexio (Intents,Ultima)>
<!ELEMENT Intents EMPTY>
<!ATTLIST Intents Restants CDATA #REQUIRED>
<!ELEMENT Ultima EMPTY>
<!ATTLIST Ultima Data CDATA #REQUIRED>

=== pablosproject/chess-player/Extra/Servidor/configura.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Server SYSTEM "configura.dtd">
<Server>
    <!-- ***** Dades de la configuració de l'entorn Chess Online *****	-->
    <Configuracio>
        <!-- ***** Port on es connecten per les peticios      *****          -->
        <Port Base="9001" />
        <!-- ***** Nombre màxim de Partides que es permet     *****	-->
        <Maxim Partides="200" />
        <!-- ***** Nombre màxim d'usuaris connectats per partida i al chat ***** -->
        <Ports Partida="20" Chat="100" />
        <!-- ***** Jugadors registrats en el sistema              *****    -->
        <Usuaris Registrats="4" />
    </Configuracio>
    <!-- ***** Llista de jugadors registrats en el sistema *****        -->
    <Jugadors>
        <Jugador>
            <Nom> Blanques </Nom>
            <Cognom> Blanques </Cognom>
            <Login> blanques </Login>
            <Password> blanques </Password>
            <Mail> blanques@salle.uRL.edu </Mail>
            <Punts> 5 </Punts>
            <Partides>
                <Guanyades> 9 </Guanyades>
                <Perdudes> 0 </Perdudes>
                <Abandonades> 20 </Abandonades>
                <Taules> 0 </Taules>
            </Partides>
            <Connexio>
                <Intents Restants="3" />
                <Ultima Data="22/12/2011" />
            </Connexio>
        </Jugador>
        <Jugador>
            <Nom> Andreu </Nom>
            <Cognom> Sancho </Cognom>
            <Login> is14104 </Login>
            <Password> caramelo </Password>
            <Mail> is14104@salle.url.edu </Mail>
            <Punts> 10 </Punts>
            <Partides>
                <Guanyades> 2 </Guanyades>
                <Perdudes> 0 </Perdudes>
                <Abandonades> 0 </Abandonades>
                <Taules> 0 </Taules>
            </Partides>
            <Connexio>
                <Intents Restants="3" />
                <Ultima Data="19/11/2010" />
            </Connexio>
        </Jugador>
        <Jugador>
            <Nom> Negres </Nom>
            <Cognom> Negres </Cognom>
            <Login> negres </Login>
            <Password> negres </Password>
            <Mail> negres@salleURL.edu </Mail>
            <Punts> 82 </Punts>
            <Partides>
                <Guanyades> 20 </Guanyades>
                <Perdudes> 0 </Perdudes>
                <Abandonades> 9 </Abandonades>
                <Taules> 0 </Taules>
            </Partides>
            <Connexio>
                <Intents Restants="3" />
                <Ultima Data="22/12/2011" />
            </Connexio>
        </Jugador>
        <Jugador>
            <Nom> Andreu </Nom>
            <Cognom> Sancho </Cognom>
            <Login> andreus </Login>
            <Password> caramelo </Password>
            <Mail> andreus@salle.url.edu </Mail>
            <Punts> -4 </Punts>
            <Partides>
                <Guanyades> 0 </Guanyades>
                <Perdudes> 0 </Perdudes>
                <Abandonades> 2 </Abandonades>
                <Taules> 0 </Taules>
            </Partides>
            <Connexio>
                <Intents Restants="3" />
                <Ultima Data="19/11/2010" />
            </Connexio>
        </Jugador>
    </Jugadors>
</Server>
